### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by vbarrier**
Hello, 

I made some change to be able to use the last version of iceScrum with the VM. It should also download the latest available version when the setup wizard is executed.

Thank you!

### CODE REVIEW

**Comment by JedMeister** [comment]
@vbarrier  Thanks for the PR. Automatically installing the latest version is very handy.

I had a quick look as I was thinking of rebuilding icescrum for v14.1 (so it has the latest version) however I noticed a few other things:
- conf.d/main also needs editing ([line 21](https://github.com/turnkeylinux-apps/icescrum/blob/master/conf.d/main#L21))
- the inithook also needs adjusting as it no longer works properly - my guess is that the hashing has changed ([see line 81 - overlay/usr/lib/inithooks/bin/icescrum.py](https://github.com/turnkeylinux-apps/icescrum/blob/master/overlay/usr/lib/inithooks/bin/icescrum.py#L81)) - but it's only a guess...

Unfortunately I'm running out of time and the 2nd point is a show stopper and I don't have time to fix it ATM. If you're happy to work on this further that'd be great, but please realise that it is highly unlikely to make it into v14.1 at this stage. Regardless we'll get it done for v14.2.

Also in case you're having issues building/rebuilding icescrum on TKLDev check out https://github.com/turnkeylinux/tracker/issues/576

**Comment by vbarrier** [comment]
@JedMeister Ok I'm going to find some time to fix the whole thing :)

**Comment by JedMeister** [comment]
@vbarrier That'd be super awesome! :smile: 
The first is easy (just remove `_*`).
The second though might be a little trickier...
Actually I just checked your profile. I'm guessing that you'd be in a much better position to tell me what changed in icescrum to stop our inithook working! :stuck_out_tongue_winking_eye: 
Even if you can tell me then that would make it pretty easy I imagine.

**Comment by vbarrier** [comment]
For second part, it's because we don't have  a default admin account created anymore. Now, we have a wizard that ask & guide the user to create an account (and other things).

**Comment by JedMeister** [comment]
So could we just create a user in the DB? What other stuff would we need to script? What would you suggest?

**Comment by vbarrier** [comment]
would it be possible to remove that step (user creation scripting) and let do it in iceScrum?

**Comment by JedMeister** [comment]
Possible? yes; desirable? no...

The idea of TurnKey appliances is that they're turnkey! Ideally the software should be completely installed ready to use...

If there is not an easy way for us to script it then we could resort to doing the last part using curl. It seems like a backwards step though...

**Comment by vbarrier** [comment]
Ok ! 
So I'm going to make some change in order to create a user using SQL then! :)
I will have some time tomorrow I hope :)

**Comment by vbarrier** [comment]
Hi guys, I need one more thing to finish this; 

How can I set automatically the default domain to the IP of VM and not "www.example.com" before asking the user in the first boot configuration.. Or could it be possible to have this IP as default url in the first boot screen?

Cheer;

**Comment by JedMeister** [comment]
Thanks for your work on this.

Why not www.example.com?

We need to have some default and it's what we use with our other appliances (that require a domain to be set) and have done for some time. 

The problem with suggesting an IP as the default domain is that TurnKey appliances get their IP via DHCP (unless the user manually sets a static IP). This will cause users problems later on.

For users on fully headless systems (e.g. AWS, LXC, Xen, Proxmox, OpenNode, etc) the appliances are often pre-seeded (so that the values are pre-filled to those desired by the user and they'll never see the default domain). Also all of the services (other than SSH) are fenced and don't display until the user runs through the interactive inithooks (or values were pre-seeded).

For other users (e.g. ISO, OVA, etc) the inithook screens are the first thing they'll see so they fill it out. 

For basic testing we recommend users just set www.example.com to point to your VM IP in their hosts file (and accept the default). Otherwise users set their domain either to their IP (as you suggest; but only applies if they have a static IP) or to their real domain (when/where they have one). We also provide free tklapp.com sub-domains.

**Comment by vbarrier** [comment]
I asked that because iceScrum need that the javascript and other ressources come from the defined APP_DOMAIN and nothing else (same protocol included). In other cases, it will redirect the browser to the APP_DOMAIN (like example.com) and then user can be lost :-(

But now, I see why you need to let it like that.

So could we add the user specified APP_DOMAIN on the confconsole screen (like for web / webmin entries)? 

On iceScrum side, it's done, we pushed an update to handle the default admin creation and war is available to download :)

**Comment by JedMeister** [comment]
Your suggestion on showing the APP_DOMAIN on the confconsole screen is a really good one! I have lodged it on our issue tracker. :+1: 

I'll do a test build today and assuming all goes well, I'll add iceScrum back to the list of apps to rebuild for v14.1 :smile: If for some reason I hit any issues I'll post back; otherwise I'll merge.

**Comment by JedMeister** [comment]
@vbarrier - Works a treat! You rock! :+1:

**Comment by vbarrier** [comment]
Thanks! 
(PS: Who or Where should I ask to update our iceScrum turnkey logo on your website? We have a new and nice one: https://www.icescrum.com/wp-content/logotype.png))

**Comment by JedMeister** [comment]
The current logo is in the `.art` directory ([here](https://github.com/turnkeylinux-apps/icescrum/blob/master/.art/logo.png)) so it can be updated with a PR. We can add it as an issue on the tracker so iit doesn't get forgotten.

If you'd like to have a look at it yourself then there is a [blank gimp template](https://github.com/turnkeylinux/artwork/blob/master/templates/logo.xcf) is in the [artwork repo](https://github.com/turnkeylinux/artwork). The desired specs are in the README.

**Pull request merged**
