### PR TITLE
Updated iceScrum logo

### PR DESCRIPTION
**Pull request by vbarrier**

### CODE REVIEW

**Comment by vbarrier** [comment]
Hello @JedMeister, Do you have an estimated release date for this? :)

Thanks!

**Comment by JedMeister** [comment]
Today hopefully! :smile: :tada: 

FWIW the images are already live on our mirror. E.g. 64 bit iceScrum iso: http://mirror.turnkeylinux.org/turnkeylinux/images/iso/turnkey-icescrum-14.1-jessie-amd64.iso

**Comment by JedMeister** [comment]
It's live: https://www.turnkeylinux.org/blog/14.1-bugfixes-maintenance-and-more

:tada:

**Comment by JedMeister** [comment]
Apologies on the delay, FWIW I could have done this separately, however I intentionally left it do with the v14.1 release. Having said that I had thought that the v14.1 release would have been about a month ago...

**Pull request merged**
